import { StyleSheet, Text, View } from 'react-native';
import { colors } from '../../../configuration';
import { normalize } from '../../utils/normalize';
import { color } from 'react-native-reanimated';

const styles = StyleSheet.create({
    container: {
      alignItems: 'flex-start',
      backgroundColor: colors.primaryA,
      flex: 1,
      flexDirection: 'column',
      marginTop: normalize(10), 
    },
    content: {
        backgroundColor: colors.white,
        flex: 1,
        flexDirection: 'column',
        padding: normalize(3),
        width: '100%',
      },
    bottom:{
        backgroundColor: colors.primaryA,
        bottom: 0,
        height: normalize(7),
        position: 'absolute',
        width: '100%',
    },
    element: {
        backgroundColor: colors.secondaryB,
        borderRadius: normalize(10),
        width: '100%',
        padding: normalize(2),
    },
    welcome: {
        alignSelf: 'center',
        color: colors.white,
        fontSize: normalize(10),
        /* marginBottom: normalize(1),
        marginTop: normalize(1), 
        padding: normalize(0.5),*/
        textAlign: 'center',
        fontFamily: 'Poppins-Bold',
    },
    link:{
        alignSelf: 'center',
        color: colors.secondaryB,
        fontSize: normalize(5),
        marginBottom: normalize(5),
        marginTop: normalize(1),
        padding: normalize(0.5),
        textAlign: 'center',
        fontFamily: 'Poppins-Bold',
    },
    answerText:{
        color: colors.white,
        fontFamily: 'Poppins',
        textAlign: 'justify',
        maxWidth: normalize(1000),
        margin: normalize(1),
    },
    section:{
        width: '90%',
        alignSelf: 'center',
        marginBottom: normalize(10)
    },
    questions:{
        marginTop: normalize(5),
    },
    title:{
        color: colors.primaryA,
        fontSize: normalize(7),
        fontFamily: 'Poppins',
        marginBottom: normalize(5),
        marginTop: normalize(1),
        padding: normalize(0.5),
    },
    row:{
        alignSelf: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        margin: normalize(2),
        justifyContent: 'space-around',
    },
    icon:{
        height:normalize(20),
        margin: normalize(1),
        width:normalize(20),
    },
    circle:{
        alignItems:'center',
        backgroundColor: colors.white,
        borderRadius: normalize(50),
        height: normalize(80),
        marginRight: normalize(1),
        padding: normalize(1),
        width: normalize(80),
    },
    info:{
        marginLeft: normalize(1),
        marginRight: normalize(1),
        maxWidth: '80%',
    },
    text:{
        color:colors.gray,
        fontSize: normalize(2.8),
        marginBottom: normalize(0.25),
        /* textDecorationStyle: 'solid',
        textDecorationColor: colors.gray,
        textDecorationLine: 'underline',*/
        fontFamily: 'Poppins',
    },
    answer:{
        backgroundColor: colors.secondaryB,
        borderRadius: normalize(3),
        color: colors.gray,
        fontSize: normalize(2.8),
        flexDirection: 'row',
        margin: normalize(5),
        padding: normalize(1),
        alignItems: 'center',
    },
    map:{
        alignSelf: 'center',
        borderRadius: normalize(500),
        height: normalize(3000),
        margin: normalize(2),
        marginBottom: normalize(20),
        marginTop: normalize(10),
        width: '85%',
    },
    input: {
        alignSelf: 'center',
        backgroundColor: colors.white,
        borderColor: colors.gray,
        borderRadius: 20,
        borderWidth: 1,
        fontSize: normalize(4),
        height: normalize(50),
        margin: normalize(0.5),
        padding: 10,
        width: '80%',
        fontFamily: 'Poppins',
    },
    input_multiline: {
        alignSelf: 'center',
        backgroundColor: colors.white,
        borderColor: colors.white,
        borderRadius: 20,
        borderWidth: 1,
        fontSize: normalize(2),
        height: normalize(600),
        margin: normalize(0.5),
        padding: 10,
        width: '80%',
    },
    submitText:{
        backgroundColor: colors.secondaryB,
        borderRadius: normalize(20),
        color: colors.white,
        padding:normalize(5),
        paddingBottom: normalize(1),
        paddingTop: normalize(1),
    },
    submit:{
        alignSelf:'flex-end',
        borderRadius: normalize(15),
        marginBottom: normalize(10),
        marginTop: normalize(5),
        right: '15%',
    },
    error:{
        alignSelf: 'center',
        color:colors.white,
        fontSize: normalize(3),
        marginBottom: normalize(0.25),
    },
    viewLocation:{
        alignSelf: 'center',
        textAlign: 'center',
        /*backgroundColor: colors.primaryA,
        textDecorationLine: 'underline',
        borderRadius: normalize(1),*/
        color: colors.primaryA,
        padding:normalize(6),
        paddingBottom: normalize(1),
        paddingTop: normalize(1),
        marginBottom: normalize(1),
    },
  });
  
export default styles